#!/bin/bash 

if [[ -z "$1" ]]; then
	echo "No specified folder."
else
	if [ -d $1 ]; then
		cd $1
		dir_number=$(find -maxdepth 1 -type d | wc -l)
		dir_number=$(expr $dir_number - 1)
		echo "$dir_number directories to check."
		dir_array[$dir_number]=0
		file_array=tmp.txt
		ls -d */ -format -1 > $file_array

		for (( i=0;i<dir_number;i++ )); do 
			read -a dir_array -d '\n' < $file_array
			echo ${dir_array[i]}
		done	
		
		echo -e "\n"
		echo "Updating..."
		echo -e "\n"	

		for (( i=0;i<dir_number;i++ )); do 
			echo -e "\n"
			echo "${dir_array[i]}"
			echo "####################"
			echo -e "\n"
			git -C ${dir_array[i]} pull
			make -C ${dir_array[i]}
		done
	else
		echo "Directory doesn't exist"
	fi
fi
